name: Periodic Health Check

on:
  #schedule:
  #  - cron: '*/10 * * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL 
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://moch-pokedex.herokuapp.com
          max-attempts: 3
          retry-delay: 5s